name: Benchmarks

on:
    workflow_dispatch:
    schedule:
      - cron:  '0 1 * * *' # run on default branch every day
jobs:
    benchmarks:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Fetch Branch from Gno Repository
          run: |
            git remote add upstream https://github.com/gnolang/gno.git
            git fetch upstream gh-benchmarks
            git checkout -b gh-pages upstream/gh-benchmarks
        - name: Push Branch to gh-pages
          run: |
            git push origin gh-pages --force
